#!/usr/bin/env python3
"""Download PvPoke's game master and overall rankings, trim them, and write data/*.js.

Output is JavaScript (`window.PvpData.raw.<key> = {...};`) rather than JSON so the site still
works when index.html is opened over file://, where fetch() of local files is blocked.

Standard library only. Run from anywhere:  python3 scripts/update_data.py
"""
import json
import os
import sys
import urllib.request
from datetime import datetime, timezone

SOURCE = "https://raw.githubusercontent.com/pvpoke/pvpoke/master/src/data"
LEAGUES = {"great": 1500, "ultra": 2500, "master": 10000}
OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "data")

# Guards against writing a broken snapshot if upstream changes shape or serves an error page.
MIN_POKEMON = 1000
MIN_MOVES = 250
MIN_RANKED = 300

POKEMON_TAGS = {"shadow", "shadoweligible", "legendary", "mythical", "ultrabeast"}
MOVE_FIELDS = ("moveId", "name", "type", "power", "energy", "energyGain", "turns",
               "buffs", "buffTarget", "buffApplyChance", "buffsSelf", "buffsOpponent")


def fetch_json(path):
    url = SOURCE + "/" + path
    with urllib.request.urlopen(url, timeout=60) as resp:
        return json.load(resp)


def trim_pokemon(p):
    out = {
        "id": p["speciesId"],
        "name": p["speciesName"],
        "dex": p["dex"],
        "types": [t for t in p["types"] if t != "none"],
        "stats": [p["baseStats"]["atk"], p["baseStats"]["def"], p["baseStats"]["hp"]],
        "fast": p["fastMoves"],
        "charged": p["chargedMoves"] + p.get("extraChargedMoves", []),
    }
    elite = p.get("eliteMoves", []) + p.get("legacyMoves", [])
    if elite:
        out["elite"] = sorted(set(elite))
    tags = sorted(POKEMON_TAGS.intersection(p.get("tags", [])))
    if tags:
        out["tags"] = tags
    if p.get("nicknames"):
        out["nicknames"] = p["nicknames"]
    if p.get("levelFloor"):
        out["levelFloor"] = p["levelFloor"]
    return out


def trim_move(m):
    return {k: m[k] for k in MOVE_FIELDS if k in m}


def trim_gamemaster(gm):
    pokemon = [
        trim_pokemon(p) for p in gm["pokemon"]
        if p.get("released") and "mega" not in p.get("tags", []) and "supermega" not in p.get("tags", [])
    ]
    moves = [trim_move(m) for m in gm["moves"]]
    if len(pokemon) < MIN_POKEMON or len(moves) < MIN_MOVES:
        sys.exit("game master looks wrong: %d pokemon, %d moves" % (len(pokemon), len(moves)))
    return {"timestamp": gm["timestamp"], "pokemon": pokemon, "moves": moves}


def trim_ranking(r):
    return {
        "id": r["speciesId"],
        "score": r["score"],
        # PvPoke order: lead, closer, switch, charger, attacker, consistency.
        "roles": r["scores"],
        # A Pokémon with a single charged move gets "none" as its second; drop it.
        "moveset": [m for m in r["moveset"] if m != "none"],
        "wins": [[m["opponent"], m["rating"]] for m in r.get("matchups", [])],
        "losses": [[m["opponent"], m["rating"]] for m in r.get("counters", [])],
    }


def trim_rankings(rankings, known_ids):
    out = [trim_ranking(r) for r in rankings if r["speciesId"] in known_ids]
    if len(out) < MIN_RANKED:
        sys.exit("rankings look wrong: only %d entries" % len(out))
    return out


def write_js(name, key, value):
    path = os.path.join(OUT_DIR, name)
    body = json.dumps(value, separators=(",", ":"), ensure_ascii=False)
    with open(path, "w", encoding="utf-8") as f:
        f.write("// Generated by scripts/update_data.py from PvPoke (MIT, (c) 2019 pvpoke). Do not edit.\n")
        f.write("window.PvpData=window.PvpData||{raw:{}};window.PvpData.raw[%s]=%s;\n" % (json.dumps(key), body))
    print("wrote %s (%d KB)" % (os.path.relpath(path), os.path.getsize(path) // 1024))


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    gamemaster = trim_gamemaster(fetch_json("gamemaster.min.json"))
    known_ids = {p["id"] for p in gamemaster["pokemon"]}

    rankings = {}
    for league, cp in LEAGUES.items():
        rankings[league] = trim_rankings(fetch_json("rankings/all/overall/rankings-%d.json" % cp), known_ids)

    write_js("gamemaster.js", "gamemaster", gamemaster)
    for league, entries in rankings.items():
        write_js("rankings-%s.js" % league, "rankings-" + league, entries)

    # Only the upstream timestamp goes in the data files, so an unchanged upstream produces no diff
    # and the scheduled workflow makes no commit.
    print("gamemaster timestamp: %s, fetched %s" % (gamemaster["timestamp"],
                                                    datetime.now(timezone.utc).isoformat(timespec="seconds")))


if __name__ == "__main__":
    main()
